app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

homepage:
    path: /{_locale}
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: blog_index
        permanent: true
        _locale: '%locale%'